In [36]:
import pandas as pd
import numpy as np

In [37]:
ty = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])
q1 = np.percentile(ty, 25)
q2 = np.percentile(ty, 50)
mediana = np.median(ty)
q3 = np.percentile(ty, 75)
print(f'Mediana: {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')


Mediana: 23.5
Primeiro quartil (Q1): 17.75
Segundo quartil (Q2): 23.5
Terceiro quartil (Q3): 29.5


In [38]:
read = pd.read_csv('pesquisa_satisfacao.csv', sep = ';')
print(read)


         Cliente Satisfação  Tempo de Espera (min)
0         Naruto       Alta                      8
1           Goku       Alta                     10
2         Vegeta      Média                     17
3         Sasuke       Alta                      8
4         Madara      Média                     15
5          Luffy      Baixa                      5
6           Zoro       Alta                     22
7          Sanji      Baixa                     26
8         Yusuke      Baixa                     14
9         Kurama      Média                      8
10           Gon      Média                     12
11          Eren      Média                     28
12        Mikasa       Alta                      6
13         Light       Alta                     10
14             L       Alta                     19
15  Peter Parker      Baixa                     21
16   Bruce Wayne       Alta                     18
17        Thanos      Média                     19
18       Edmundo      Baixa    

In [39]:
tempo_espera_array = np.array(read['Tempo de Espera (min)'])
print (tempo_espera_array, sep = ' ')

q1 = np.percentile(tempo_espera_array, 25)
q2 = np.percentile(tempo_espera_array, 50)
mediana = np.median(tempo_espera_array)
q3 = np.percentile(tempo_espera_array, 75)
print(f'Mediana: {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')


[ 8 10 17  8 15  5 22 26 14  8 12 28  6 10 19 21 18 19 13 19]
Mediana: 14.5
Primeiro quartil (Q1): 9.5
Segundo quartil (Q2): 14.5
Terceiro quartil (Q3): 19.0


In [40]:
pesquisa_25 = read.loc[read['Tempo de Espera (min)'] >= q3]
pesquisa_25

Cliente Satisfação  Tempo de Espera (min)
6           Zoro       Alta                     22
7          Sanji      Baixa                     26
11          Eren      Média                     28
14             L       Alta                     19
15  Peter Parker      Baixa                     21
17        Thanos      Média                     19
19       Vegetti      Média                     19

In [41]:
read.sort_values(by = 'Tempo de Espera (min)', ascending = False)

Cliente Satisfação  Tempo de Espera (min)
11          Eren      Média                     28
7          Sanji      Baixa                     26
6           Zoro       Alta                     22
15  Peter Parker      Baixa                     21
17        Thanos      Média                     19
19       Vegetti      Média                     19
14             L       Alta                     19
16   Bruce Wayne       Alta                     18
2         Vegeta      Média                     17
4         Madara      Média                     15
8         Yusuke      Baixa                     14
18       Edmundo      Baixa                     13
10           Gon      Média                     12
13         Light       Alta                     10
1           Goku       Alta                     10
0         Naruto       Alta                      8
3         Sasuke       Alta                      8
9         Kurama      Média                      8
12        Mikasa       Alta                      6
5          Luffy      Baixa                      5

In [42]:
pesquisa_alta = read.loc[read['Satisfação'] == 'Alta']
pesquisa_alta


Cliente Satisfação  Tempo de Espera (min)
0        Naruto       Alta                      8
1          Goku       Alta                     10
3        Sasuke       Alta                      8
6          Zoro       Alta                     22
12       Mikasa       Alta                      6
13        Light       Alta                     10
14            L       Alta                     19
16  Bruce Wayne       Alta                     18

In [43]:
pesquisa_baixa = read.loc[read['Satisfação'] == 'Baixa']
pesquisa_baixa

Cliente Satisfação  Tempo de Espera (min)
5          Luffy      Baixa                      5
7          Sanji      Baixa                     26
8         Yusuke      Baixa                     14
15  Peter Parker      Baixa                     21
18       Edmundo      Baixa                     13

In [44]:
array_alta = np.array(pesquisa_alta['Tempo de Espera (min)'])
array_alta

array([ 8, 10,  8, 22,  6, 10, 19, 18])

In [45]:
q1 = np.percentile(array_alta, 25)
q2 = np.percentile(array_alta, 50)
mediana = np.median(array_alta)
q3 = np.percentile(array_alta, 75)
print(f'Mediana: {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Mediana: 10.0
Primeiro quartil (Q1): 8.0
Segundo quartil (Q2): 10.0
Terceiro quartil (Q3): 18.25


In [46]:
dados = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep = ';', encoding='latin1')
dados

cisp  mes   ano  mes_ano  aisp  risp                 munic    mcirc  \
0         1    1  2003  2003m01     5     1        Rio de Janeiro  3304557   
1         4    1  2003  2003m01     5     1        Rio de Janeiro  3304557   
2         5    1  2003  2003m01     5     1        Rio de Janeiro  3304557   
3         6    1  2003  2003m01     1     1        Rio de Janeiro  3304557   
4         7    1  2003  2003m01     1     1        Rio de Janeiro  3304557   
...     ...  ...   ...      ...   ...   ...                   ...      ...   
36624   159    8  2025  2025m08    35     4  Cachoeiras de Macacu  3300803   
36625   165    8  2025  2025m08    33     5           Mangaratiba  3302601   
36626   166    8  2025  2025m08    33     5        Angra dos Reis  3300100   
36627   167    8  2025  2025m08    43     5                Paraty  3303807   
36628   168    8  2025  2025m08    28     5             Rio Claro  3304409   

         regiao  hom_doloso  ...   cmp  cmba  ameaca  pessoas_desaparecidas  \
0       Capital           0  ...   NaN   NaN      21                      2   
1       Capital           3  ...   NaN   NaN      15                      6   
2       Capital           3  ...   NaN   NaN      47                      2   
3       Capital           6  ...   NaN   NaN      26                      2   
4       Capital           4  ...   NaN   NaN      10                      1   
...         ...         ...  ...   ...   ...     ...                    ...   
36624  Interior           1  ...   5.0   0.0      16                      0   
36625  Interior           0  ...   5.0   0.0      21                      2   
36626  Interior           3  ...  11.0   3.0      63                      8   
36627  Interior           0  ...   3.0   0.0      13                      2   
36628  Interior           1  ...   1.0   0.0       5                      0   

       encontro_cadaver  encontro_ossada  pol_militares_mortos_serv  \
0                     0                0                          0   
1                     0                1                          0   
2                     1                0                          0   
3                     1                0                          0   
4                     3                0                          0   
...                 ...              ...                        ...   
36624                 0                0                          0   
36625                 0                0                          0   
36626                 0                0                          0   
36627                 0                1                          0   
36628                 0                0                          0   

       pol_civis_mortos_serv  registro_ocorrencias  fase  
0                          0                   578     3  
1                          0                   441     3  
2                          0                   637     3  
3                          0                   473     3  
4                          0                   147     3  
...                      ...                   ...   ...  
36624                      0                   148     2  
36625                      0                   179     2  
36626                      0                   595     2  
36627                      0                   234     2  
36628                      0                    50     2  

[36629 rows x 63 columns]

In [47]:
dados_cel = dados.sort_values(by = 'furto_celular')
dados_cel

cisp  mes   ano  mes_ano  aisp  risp                 munic    mcirc  \
27716   156    3  2020  2020m03    11     7  Santa Maria Madalena  3304607   
27717   157    3  2020  2020m03    11     7     Trajano de Morais  3305901   
27718   158    3  2020  2020m03    11     7            Bom Jardim  3300506   
27719   159    3  2020  2020m03    35     4  Cachoeiras de Macacu  3300803   
27723   168    3  2020  2020m03    28     5             Rio Claro  3304409   
...     ...  ...   ...      ...   ...   ...                   ...      ...   
20187    42    9  2015  2015m09    31     2        Rio de Janeiro  3304557   
36089    12    5  2025  2025m05    19     1        Rio de Janeiro  3304557   
35675     9    2  2025  2025m02     2     1        Rio de Janeiro  3304557   
31709    16    9  2022  2022m09    31     2        Rio de Janeiro  3304557   
34997    16    9  2024  2024m09    31     2        Rio de Janeiro  3304557   

         regiao  hom_doloso  ...   cmp  cmba  ameaca  pessoas_desaparecidas  \
27716  Interior           0  ...   1.0   0.0       1                      1   
27717  Interior           0  ...   1.0   0.0       1                      0   
27718  Interior           0  ...   1.0   0.0       7                      0   
27719  Interior           1  ...   3.0   0.0      15                      0   
27723  Interior           0  ...   1.0   0.0       4                      0   
...         ...         ...  ...   ...   ...     ...                    ...   
20187   Capital           0  ...   6.0   1.0      79                      3   
36089   Capital           0  ...  15.0   0.0      28                      7   
35675   Capital           3  ...   4.0   3.0      42                      5   
31709   Capital           2  ...  14.0   4.0      91                     10   
34997   Capital           3  ...  18.0   6.0      98                     13   

       encontro_cadaver  encontro_ossada  pol_militares_mortos_serv  \
27716                 0                0                          0   
27717                 0                0                          0   
27718                 0                0                          0   
27719                 0                0                          0   
27723                 0                0                          0   
...                 ...              ...                        ...   
20187                 2                0                          0   
36089                 0                0                          0   
35675                 0                0                          0   
31709                 1                0                          0   
34997                 0                0                          0   

       pol_civis_mortos_serv  registro_ocorrencias  fase  
27716                      0                    16     3  
27717                      0                    12     3  
27718                      0                    42     3  
27719                      0                    70     3  
27723                      0                    32     3  
...                      ...                   ...   ...  
20187                      0                  2165     3  
36089                      0                  1883     3  
35675                      0                  1808     3  
31709                      0                  3036     3  
34997                      0                  3185     3  

[36629 rows x 63 columns]

In [48]:
deleg = dados.groupby('cisp')['furto_celular'].sum()
deleg

cisp
1      14789
4      13093
5      22494
6       6072
7       1425
       ...  
159      450
165     1216
166     2531
167      483
168      119
Name: furto_celular, Length: 138, dtype: int64

In [49]:
dados_cel = dados.groupby('cisp')['furto_celular'].sum().reset_index()
dados_cel

cisp  furto_celular
0       1          14789
1       4          13093
2       5          22494
3       6           6072
4       7           1425
..    ...            ...
133   159            450
134   165           1216
135   166           2531
136   167            483
137   168            119

[138 rows x 2 columns]

In [50]:
dados_cel_array = np.array(dados_cel['furto_celular'])
dados_cel_array

array([14789, 13093, 22494,  6072,  1425, 13892, 13855,   383, 15757,
        7090, 16492,  6640, 24451,  7674, 12287,  8153,  4951,  6491,
        5578,  7105,  4380,  3699,  3666,  4465,  3906,  7607,  3585,
        1588, 11980,  5926,  6746, 11673,  5432,  6452,  2959,  2741,
        2188,  5263,  7502,  2738,  3548,    73,  1061,  2604,   560,
        5214,  2026,  2894,  1631,  1735,  3200,  3337,  8510,  1561,
         717,   988,   597,  4369,  1102,  1434,   351,   196,  2483,
        3160,  2098,  4648,   990,  7814,  4695,  2052,  1341,  1753,
        2095,   786,  2346,  2048,   711,    63,  3940,   355,   464,
         750,   226,    89,   428,   386,   350,    72,  3216,  1076,
         442,  1422,   135,  1761,    81,   209,  2261,   771,   291,
         444,   200,  3641,  1267,  1009,  4753,  1420,  2081,   546,
         236,   584,  3677,   350,   650,   297,    51,   357,   163,
         477,    98,  1278,   614,   482,   615,   160,   193,  2042,
         107,   253,

In [52]:
q1 = np.percentile(dados_cel, 25)
q2 = np.percentile(dados_cel, 50)
mediana = np.median(dados_cel)
q3 = np.percentile(dados_cel, 75)
print(f'Mediana: {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Mediana: 149.5
Primeiro quartil (Q1): 72.75
Segundo quartil (Q2): 149.5
Terceiro quartil (Q3): 1598.75
